# Generated by Django 2.2.3 on 2021-07-30 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('apiid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(default='', max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('avatar', models.CharField(max_length=1000, null=True)),
                ('usertype', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('devid', models.AutoField(primary_key=True, serialize=False)),
                ('APIcount', models.IntegerField(default=0)),
                ('billings', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
        migrations.CreateModel(
            name='APIorder',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('count', models.IntegerField()),
                ('end_date', models.DateField()),
                ('api', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.API')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Developer')),
            ],
        ),
    ]
