# Generated by Django 2.2.3 on 2021-08-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apiorder',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.API'),
        ),
        migrations.AlterField(
            model_name='apiorder',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='apiorder',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
